apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleapp
  name: simpleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleapp
    spec:
      containers:
      - image: dinhhuy1997/harness-demo:v1
        name: harness-demo
        resources: {}
status: {}
